import type { ISchemaDocsData } from './schema-docs-types';

/** Renders schema documentation as Markdown. */
export class DocsMdRenderer {
  render(data: ISchemaDocsData): string {
    const lines: string[] = [
      '# Database Schema Documentation',
      '',
      `Generated: ${data.generatedAt} | Tables: ${data.tables.length}` +
        ` | Rows: ${data.totalRows.toLocaleString()}` +
        ` | FKs: ${data.totalFks}`,
      '',
      '## Table of Contents',
      '',
      ...data.tables.map(
        t =>
          `- [${t.name}](#${this._anchor(t.name)})` +
          ` (${t.rowCount.toLocaleString()} rows)`,
      ),
      '',
    ];

    for (const table of data.tables) {
      lines.push(`## ${table.name}`, '');
      lines.push(`> ${table.description}`, '');
      lines.push('| Column | Type | PK | FK | Description |');
      lines.push('|---|---|---|---|---|');

      for (const col of table.columns) {
        const pk = col.pk ? '\u2713' : '';
        const fk = col.fk
          ? `\u2192 ${this._escCell(col.fk.toTable)}.${this._escCell(col.fk.toColumn)}`
          : '';
        lines.push(
          `| ${this._escCell(col.name)} | ${this._escCell(col.type)}` +
          ` | ${pk} | ${fk} | ${this._escCell(col.description)} |`,
        );
      }

      lines.push('');
      if (table.referencedBy.length > 0) {
        const refs = table.referencedBy
          .map(r => `${r.fromTable}.${r.fromColumn}`)
          .join(', ');
        lines.push(`**Referenced by:** ${refs}`);
      }
      lines.push(
        `**Row count:** ${table.rowCount.toLocaleString()}`,
      );
      lines.push('');
    }

    lines.push(
      '---',
      '*Generated by [Drift Viewer]' +
        '(https://pub.dev/packages/saropa_drift_advisor)*',
    );

    return lines.join('\n');
  }

  /** GitHub-compatible anchor from a table name. */
  private _anchor(name: string): string {
    return name.toLowerCase().replace(/[^a-z0-9_-]/g, '-');
  }

  /** Escape pipe characters that would break Markdown table cells. */
  private _escCell(s: string): string {
    return s.replace(/\|/g, '\\|');
  }
}
