name: saropa_drift_viewer
description: >-
  DEPRECATED. This package has been permanently replaced by
  saropa_drift_advisor.
  See https://pub.dev/packages/saropa_drift_advisor
version: 0.2.5
homepage: https://pub.dev/packages/saropa_drift_advisor

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.25.0
