/**
 * Generates Drift migration Dart code from a schema diff result.
 * Produces `customStatement()` calls for each detected change.
 */

import { IDartColumn } from '../schema-diff/dart-schema';
import { ColumnMetadata } from '../api-client';
import {
  ISchemaDiffResult,
  ITableColumnDiff,
  ITypeMismatch,
} from '../schema-diff/schema-diff';

/** A single migration action derived from a schema diff. */
export interface IMigrationAction {
  type:
    | 'createTable'
    | 'dropTable'
    | 'addColumn'
    | 'dropColumn'
    | 'changeType';
  table: string;
  column?: string;
  oldType?: string;
  newType?: string;
  columns?: IColumnDef[];
  nullable?: boolean;
}

/** Column definition for a CREATE TABLE action. */
export interface IColumnDef {
  name: string;
  sqlType: string;
  pk: boolean;
  nullable: boolean;
  autoIncrement: boolean;
}

/**
 * Convert a schema diff result into an ordered list of migration
 * actions. Order: creates, then alters (add/change), then drops.
 */
export function diffToActions(
  diff: ISchemaDiffResult,
): IMigrationAction[] {
  const actions: IMigrationAction[] = [];

  for (const table of diff.tablesOnlyInCode) {
    actions.push({
      type: 'createTable',
      table: table.sqlTableName,
      columns: table.columns.map(dartColToDef),
    });
  }

  for (const td of diff.tableDiffs) {
    pushTableDiffActions(td, actions);
  }

  for (const table of diff.tablesOnlyInDb) {
    actions.push({ type: 'dropTable', table: table.name });
  }

  return actions;
}

function pushTableDiffActions(
  td: ITableColumnDiff,
  actions: IMigrationAction[],
): void {
  for (const col of td.columnsOnlyInCode) {
    actions.push(addColumnAction(td.tableName, col));
  }
  for (const m of td.typeMismatches) {
    actions.push(changeTypeAction(td.tableName, m));
  }
  for (const col of td.columnsOnlyInDb) {
    actions.push(dropColumnAction(td.tableName, col));
  }
}

function dartColToDef(c: IDartColumn): IColumnDef {
  return {
    name: c.sqlName,
    sqlType: c.sqlType,
    pk: c.autoIncrement,
    nullable: c.nullable,
    autoIncrement: c.autoIncrement,
  };
}

function addColumnAction(
  table: string,
  col: IDartColumn,
): IMigrationAction {
  return {
    type: 'addColumn',
    table,
    column: col.sqlName,
    newType: col.sqlType,
    nullable: col.nullable,
  };
}

function changeTypeAction(
  table: string,
  m: ITypeMismatch,
): IMigrationAction {
  return {
    type: 'changeType',
    table,
    column: m.columnName,
    oldType: m.dbType,
    newType: m.codeType,
  };
}

function dropColumnAction(
  table: string,
  col: ColumnMetadata,
): IMigrationAction {
  return {
    type: 'dropColumn',
    table,
    column: col.name,
  };
}

/**
 * Generate Dart migration code from a schema diff result.
 * Returns a self-contained Dart source string using
 * `customStatement()` calls inside an `up()` method.
 */
export function generateMigrationDart(
  diff: ISchemaDiffResult,
  fromVersion: number,
  toVersion: number,
): string {
  const actions = diffToActions(diff);
  if (actions.length === 0) return '';

  const lines: string[] = [];

  lines.push("import 'package:drift/drift.dart';");
  lines.push('');
  lines.push(
    `// Migration from schema v${fromVersion} to v${toVersion}`,
  );
  lines.push('// Generated by Drift Viewer — review before using!');
  lines.push('');

  for (const action of actions) {
    lines.push(...generateAction(action));
    lines.push('');
  }

  return lines.join('\n');
}

function generateAction(action: IMigrationAction): string[] {
  switch (action.type) {
    case 'createTable':
      return generateCreateTable(action);
    case 'dropTable':
      return generateDropTable(action);
    case 'addColumn':
      return generateAddColumn(action);
    case 'dropColumn':
      return generateDropColumn(action);
    case 'changeType':
      return generateTypeChange(action);
  }
}

function generateCreateTable(action: IMigrationAction): string[] {
  const cols = action.columns ?? [];
  const colLines = cols.map((c, i) => {
    const parts = [`    "${c.name}" ${c.sqlType}`];
    if (c.pk) parts.push('PRIMARY KEY');
    if (c.autoIncrement) parts.push('AUTOINCREMENT');
    if (!c.nullable && !c.pk) parts.push('NOT NULL');
    return parts.join(' ') + (i < cols.length - 1 ? ',' : '');
  });

  return [
    `// New table: ${action.table}`,
    "await customStatement('''",
    `  CREATE TABLE "${action.table}" (`,
    ...colLines,
    '  )',
    "''');",
  ];
}

function generateAddColumn(action: IMigrationAction): string[] {
  const nullable = action.nullable ?? true;
  const suffix = nullable ? '' : " NOT NULL DEFAULT ''";
  return [
    `// Added column: ${action.table}.${action.column}`,
    'await customStatement(',
    `  'ALTER TABLE "${action.table}"'`,
    `  ' ADD COLUMN "${action.column}" ${action.newType}${suffix}',`,
    ');',
  ];
}

function generateDropColumn(action: IMigrationAction): string[] {
  return [
    `// Removed column: ${action.table}.${action.column}`,
    '// Note: SQLite < 3.35 does not support DROP COLUMN.',
    '// Use table recreation if targeting older SQLite versions.',
    'await customStatement(',
    `  'ALTER TABLE "${action.table}"'`,
    `  ' DROP COLUMN "${action.column}"',`,
    ');',
  ];
}

function generateDropTable(action: IMigrationAction): string[] {
  return [
    `// Removed table: ${action.table}`,
    `// WARNING: This will delete all data in "${action.table}"!`,
    `await customStatement('DROP TABLE IF EXISTS "${action.table}"');`,
  ];
}

function generateTypeChange(action: IMigrationAction): string[] {
  const col = action.column ?? '?';
  const old = action.oldType ?? '?';
  const next = action.newType ?? '?';
  return [
    `// Type change: ${action.table}.${col} `
      + `(${old} \u2192 ${next})`,
    '// WARNING: SQLite does not support ALTER COLUMN.',
    '// Manual migration required — recreate the table with the',
    '// new column type and migrate data.',
    '// See https://sqlite.org/lang_altertable.html'
      + '#making_other_kinds_of_table_schema_changes',
  ];
}
