import type { AssertionType, IAssertion } from './test-gen-types';

const GROUP_NAMES: Record<AssertionType, string> = {
  rowCount: 'Row counts',
  fkIntegrity: 'FK integrity',
  notNull: 'Null constraints',
  unique: 'Uniqueness',
  valueRange: 'Value ranges',
};

/** Renders a list of assertions as a Dart test file. */
export class DartTestRenderer {
  /** Produce a complete Dart test file from the given assertions. */
  render(assertions: IAssertion[]): string {
    const lines = [
      ...this._boilerplate(),
      'void main() {',
    ];

    const groups = this._groupByType(assertions);
    for (const [type, items] of groups) {
      lines.push(`  group('${GROUP_NAMES[type]}', () {`);

      for (const a of items) {
        const name = this._testName(a);
        lines.push(`    test('${escDart(name)}', () async {`);
        lines.push(`      final result = await query(`);
        lines.push(`        ${dartString(a.sql)},`);
        lines.push('      );');

        if (a.expectation.startsWith('equals ')) {
          const val = a.expectation.slice('equals '.length);
          lines.push(`      expect(result.first['cnt'], ${val});`);
        } else if (a.expectation === 'is empty') {
          lines.push('      expect(result, isEmpty,');
          lines.push(
            `        reason: '${escDart(a.reason)}');`,
          );
        }

        lines.push('    });');
        lines.push('');
      }

      lines.push('  });');
      lines.push('');
    }

    lines.push('}');
    lines.push('');
    return lines.join('\n');
  }

  private _boilerplate(): string[] {
    return [
      '// Generated by Saropa Drift Advisor — verify database invariants.',
      '// Modify assertions as needed for your use case.',
      '',
      "import 'package:flutter_test/flutter_test.dart';",
      '',
      '/// Test helper: runs a raw SQL query against the test database.',
      '/// Replace this with your actual database access pattern.',
      'Future<List<Map<String, dynamic>>> query(String sql) async {',
      '  // TODO: Replace with your database query method',
      "  throw UnimplementedError('Wire up your test database');",
      '}',
      '',
    ];
  }

  private _testName(a: IAssertion): string {
    switch (a.type) {
      case 'rowCount': {
        const count = a.expectation.slice('equals '.length);
        return `${a.table} has ${count} rows`;
      }
      case 'fkIntegrity':
        return `every ${a.table} references a valid ${a.column}`;
      case 'notNull':
        return `${a.table}.${a.column} is never null`;
      case 'unique':
        return `${a.table}.${a.column} is unique`;
      case 'valueRange':
        return `${a.table}.${a.column} stays within range`;
    }
  }

  private _groupByType(
    assertions: IAssertion[],
  ): [AssertionType, IAssertion[]][] {
    const map = new Map<AssertionType, IAssertion[]>();
    for (const a of assertions) {
      let list = map.get(a.type);
      if (!list) {
        list = [];
        map.set(a.type, list);
      }
      list.push(a);
    }
    return [...map.entries()];
  }
}

/** Escape a string for use inside a Dart single-quoted string. */
export function escDart(s: string): string {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\$/g, '\\$');
}

/** Wrap a SQL string as a Dart single-quoted string literal. */
export function dartString(sql: string): string {
  return `'${escDart(sql)}'`;
}
