import type { IConstraintDraft } from './constraint-types';

/** Generates Dart migration code and raw SQL for proposed constraints. */
export class ConstraintCodegen {
  generateDart(constraints: IConstraintDraft[]): string {
    const lines: string[] = [
      '// Generated by Drift Viewer \u2014 Constraint Wizard',
      `// Table: ${constraints[0]?.table ?? 'unknown'}`,
      `// Constraints: ${constraints.length} new constraint(s)`,
      '',
    ];

    for (const c of constraints) {
      switch (c.kind) {
        case 'unique':
          this._uniqueDart(c, lines);
          break;
        case 'check':
          this._checkDart(c, lines);
          break;
        case 'not_null':
          this._notNullDart(c, lines);
          break;
      }
    }

    return lines.join('\n');
  }

  generateSql(constraints: IConstraintDraft[]): string {
    const lines: string[] = [
      '-- Generated by Drift Viewer \u2014 Constraint Wizard',
      '',
    ];

    for (const c of constraints) {
      switch (c.kind) {
        case 'unique':
          this._uniqueSql(c, lines);
          break;
        case 'check':
          this._checkSql(c, lines);
          break;
        case 'not_null':
          this._notNullSql(c, lines);
          break;
      }
    }

    return lines.join('\n');
  }

  private _uniqueDart(c: IConstraintDraft, lines: string[]): void {
    const cols = (c.columns ?? []).map((col) => `"${col}"`).join(', ');
    const name = `uq_${c.table}_${(c.columns ?? []).join('_')}`;
    lines.push(
      `await customStatement('CREATE UNIQUE INDEX`
      + ` "${name}" ON "${c.table}"(${cols})');`,
      '',
    );
  }

  private _checkDart(c: IConstraintDraft, lines: string[]): void {
    lines.push(
      '// NOTE: SQLite does not support ALTER TABLE ADD CHECK.',
      '// To add a CHECK constraint, the table must be recreated.',
      `// CHECK expression: ${c.expression}`,
      '',
    );
  }

  private _notNullDart(c: IConstraintDraft, lines: string[]): void {
    lines.push(
      '// NOTE: SQLite does not support ALTER TABLE ALTER COLUMN'
      + ' SET NOT NULL.',
      `// Column "${c.column}" must be recreated with NOT NULL.`,
      '// Ensure no NULL values exist first.',
      '',
    );
  }

  private _uniqueSql(c: IConstraintDraft, lines: string[]): void {
    const cols = (c.columns ?? []).map((col) => `"${col}"`).join(', ');
    const name = `uq_${c.table}_${(c.columns ?? []).join('_')}`;
    lines.push(
      `CREATE UNIQUE INDEX "${name}" ON "${c.table}"(${cols});`,
      '',
    );
  }

  private _checkSql(c: IConstraintDraft, lines: string[]): void {
    lines.push(
      `-- CHECK: ${c.expression}`,
      '-- (Requires table recreation in SQLite)',
      '',
    );
  }

  private _notNullSql(c: IConstraintDraft, lines: string[]): void {
    lines.push(
      `-- NOT NULL on "${c.column}"`,
      '-- (Requires table recreation in SQLite)',
      '',
    );
  }
}
